version: 2

sphinx:
  configuration: docs/source/conf.py

submodules:
  exclude: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
