name: Test, Publish and Deploy new tagged version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  publish-package:
    needs: test
    uses: ./.github/workflows/python-publish.yaml
    secrets: inherit

  github-release:
    needs: publish-package
    uses: ./.github/workflows/github-release.yaml
    secrets: inherit

  delay-after-pypi-publish:
    needs: publish-package
    uses: ./.github/workflows/delay.yaml
    secrets: inherit
    with:
      seconds: 30

  test-published-package:
    needs: delay-after-pypi-publish
    uses: ./.github/workflows/test-run-of-published-version.yaml
    secrets: inherit

  deploy-web:
    needs: test-published-package
    uses: ./.github/workflows/redeploy-web.yaml
    secrets: inherit
      
  publish-docker:
    needs: test-published-package
    uses: ./.github/workflows/docker-build-and-publish.yaml
    secrets: inherit
    with:
      docker-labels: edulint/edulint-cli:latest,edulint/edulint-cli:${{ github.ref_name }}

      
