name: Test current version

on:
  push:

jobs:
  test-current-version:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

# either set permissive default permissions in repositories Actions settings or set them explicitly here
permissions:
  checks: write
  issues: read
  pull-requests: write
  contents: read

